/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/dotto/theme.ts
 * Command: astryx theme build src/dotto/theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/// <reference path="./dotto.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const dottoTheme: DefinedTheme;
