/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/dotto/theme.ts
 * Command: astryx theme build src/dotto/theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Button' {
  interface ButtonVariantMap {
    'outline': true;
    'notch': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'plan': true;
    'tool': true;
    'file': true;
    'judge': true;
  }
}
