/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/dotto/theme.ts
 * Command: astryx theme build src/dotto/theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/**
 * dotto theme — built by `bunx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { dottoTheme } from './dotto';
 *   import './dotto.css';
 */
export const dottoTheme = {
  name: 'dotto',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#67437d, #d2aaf7)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#e5edff, #131a2a)",
    "--color-neutral": "light-dark(#1E1A201A, #E6E1EA33)",
    "--color-background-surface": "light-dark(#dbe3f5, #0c1323)",
    "--color-background-body": "light-dark(#e5edff, #131a2a)",
    "--color-overlay": "light-dark(#1E1A2066, #1E1A2199)",
    "--color-overlay-hover": "light-dark(#1E1A200D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1E1A201A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#dbe3f5, #0c1323)",
    "--color-text-primary": "light-dark(#3a3c4c, #d5caf1)",
    "--color-text-secondary": "light-dark(#555768, #aea5c4)",
    "--color-text-disabled": "light-dark(#9298a6, #5f6677)",
    "--color-text-accent": "light-dark(#67437d, #d2aaf7)",
    "--color-icon-accent": "light-dark(#67437d, #d2aaf7)",
    "--color-icon-primary": "light-dark(#3a3c4c, #d5caf1)",
    "--color-icon-secondary": "light-dark(#555768, #aea5c4)",
    "--color-icon-disabled": "light-dark(#9298a6, #5f6677)",
    "--color-background-card": "light-dark(#c7cedf, #2c3343)",
    "--color-background-popover": "light-dark(#c7cedf, #2c3343)",
    "--color-background-inverted": "light-dark(#1E1A20, #FEFBFF)",
    "--color-border": "light-dark(color-mix(in srgb, #3a3c4c 18%, transparent), color-mix(in srgb, #d5caf1 18%, transparent))",
    "--color-border-emphasized": "light-dark(#b4baca, #464d5e)",
    "--color-skeleton": "light-dark(#B1A8B5, #4B4450)",
    "--color-track": "light-dark(#B1A8B5, #4B4450)",
    "--color-shadow": "light-dark(transparent, transparent)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.4375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.625rem",
    "--font-size-xs": "0.75rem",
    "--font-size-sm": "0.875rem",
    "--font-size-base": "1.0625rem",
    "--font-size-lg": "1.25rem",
    "--font-size-xl": "1.5rem",
    "--font-size-2xl": "1.8125rem",
    "--font-size-3xl": "2.1875rem",
    "--font-size-4xl": "2.625rem",
    "--font-size-5xl": "3.1875rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-normal)",
    "--text-heading-1-leading": "1.3793",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-normal)",
    "--text-heading-2-leading": "1.3333",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-normal)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-normal)",
    "--text-heading-4-leading": "1.4118",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-normal)",
    "--text-heading-5-leading": "1.4286",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-normal)",
    "--text-heading-6-leading": "1.6667",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4118",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4118",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-medium)",
    "--text-code-leading": "1.4118",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4286",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2549",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2381",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2571",
    "--radius-none": "0px",
    "--radius-inner": "2px",
    "--radius-element": "4px",
    "--radius-container": "8px",
    "--radius-page": "12px",
    "--radius-chat": "8px",
    "--radius-full": "9999px",
    "--duration-fast-min": "120ms",
    "--duration-fast": "160ms",
    "--duration-fast-max": "215ms",
    "--duration-medium-min": "180ms",
    "--duration-medium": "240ms",
    "--duration-medium-max": "320ms",
    "--duration-slow-min": "390ms",
    "--duration-slow": "520ms",
    "--duration-slow-max": "695ms",
    "--font-family-body": "Geist, ui-sans-serif, system-ui, sans-serif",
    "--font-family-heading": "\"Geist Pixel Square\", DotGothic16, ui-monospace, monospace",
    "--font-family-code": "\"Geist Mono\", ui-monospace, Menlo, Consolas, monospace",
    "--color-error": "light-dark(#ad1034, #ed5765)",
    "--color-error-muted": "light-dark(color-mix(in srgb, #ad1034 12%, transparent), color-mix(in srgb, #ed5765 16%, transparent))",
    "--color-on-error": "light-dark(#ffffff, #ffffff)",
    "--color-success": "light-dark(#21652d, #95d898)",
    "--color-success-muted": "light-dark(color-mix(in srgb, #21652d 10%, transparent), color-mix(in srgb, #95d898 14%, transparent))",
    "--color-on-success": "light-dark(#e5edff, #131a2a)",
    "--color-warning": "light-dark(#85652b, #f6d297)",
    "--color-warning-muted": "light-dark(color-mix(in srgb, #85652b 10%, transparent), color-mix(in srgb, #f6d297 15%, transparent))",
    "--color-on-warning": "light-dark(#e5edff, #131a2a)",
    "--shadow-low": "none",
    "--shadow-med": "none",
    "--shadow-high": "none",
    "--size-element-sm": "36px",
    "--size-element-md": "44px",
    "--size-element-lg": "44px",
    "--border-width": "2px",
    "--focus-outline-width": "2px",
    "--focus-outline-style": "solid",
    "--focus-outline-color": "var(--color-accent)",
    "--focus-outline-offset": "2px"
  },
  localTokens: {
    "--astryx-theme-dotto-color-accent-core": "light-dark(#8d5e8f, #f8bce3)",
    "--astryx-theme-dotto-color-accent-hover": "light-dark(#563869, #f8bce3)",
    "--astryx-theme-dotto-color-blossom": "light-dark(#d88ec7, #ffbbf5)",
    "--astryx-theme-dotto-color-blossom-soft": "light-dark(#dfabcd, #ffd2f5)",
    "--astryx-theme-dotto-color-plan": "light-dark(#3c5aa1, #8cbaf7)",
    "--astryx-theme-dotto-color-tool": "light-dark(#02717a, #7ed4de)",
    "--astryx-theme-dotto-color-file": "light-dark(#256b5b, #89cebb)",
    "--astryx-theme-dotto-color-judge": "light-dark(#5c649c, #aabaf8)",
    "--astryx-theme-dotto-color-select": "light-dark(#ecdff3, #3b2b46)",
    "--astryx-theme-dotto-color-void": "light-dark(#e5edff, #131a2a)",
    "--astryx-theme-dotto-color-obsidian": "light-dark(#dbe3f5, #0c1323)",
    "--astryx-theme-dotto-color-charcoal": "light-dark(#c7cedf, #2c3343)",
    "--astryx-theme-dotto-color-steel": "light-dark(#b4baca, #464d5e)",
    "--astryx-theme-dotto-color-ash": "light-dark(#9298a6, #5f6677)",
    "--astryx-theme-dotto-color-fog": "light-dark(#555768, #aea5c4)",
    "--astryx-theme-dotto-color-bone": "light-dark(#3a3c4c, #d5caf1)",
    "--astryx-theme-dotto-color-blood": "light-dark(#ad1034, #ed5765)",
    "--astryx-theme-dotto-color-jade": "light-dark(#21652d, #95d898)",
    "--astryx-theme-dotto-color-amber": "light-dark(#85652b, #f6d297)"
  },
  __localTokenOwners: {
    "--astryx-theme-dotto-color-accent-core": "dotto",
    "--astryx-theme-dotto-color-accent-hover": "dotto",
    "--astryx-theme-dotto-color-blossom": "dotto",
    "--astryx-theme-dotto-color-blossom-soft": "dotto",
    "--astryx-theme-dotto-color-plan": "dotto",
    "--astryx-theme-dotto-color-tool": "dotto",
    "--astryx-theme-dotto-color-file": "dotto",
    "--astryx-theme-dotto-color-judge": "dotto",
    "--astryx-theme-dotto-color-select": "dotto",
    "--astryx-theme-dotto-color-void": "dotto",
    "--astryx-theme-dotto-color-obsidian": "dotto",
    "--astryx-theme-dotto-color-charcoal": "dotto",
    "--astryx-theme-dotto-color-steel": "dotto",
    "--astryx-theme-dotto-color-ash": "dotto",
    "--astryx-theme-dotto-color-fog": "dotto",
    "--astryx-theme-dotto-color-bone": "dotto",
    "--astryx-theme-dotto-color-blood": "dotto",
    "--astryx-theme-dotto-color-jade": "dotto",
    "--astryx-theme-dotto-color-amber": "dotto"
  },
  __localTokenLineage: ["dotto"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "type:display": {
        "fontFamily": "var(--font-family-heading)",
        "fontWeight": "400",
        "letterSpacing": "0"
      }
    },
    "button": {
      "base": {
        "borderRadius": "4px",
        "fontWeight": "500",
        "borderWidth": "2px",
        "borderStyle": "solid",
        "boxShadow": "none",
        "--button-focus-offset": "2px"
      },
      "variant:primary": {
        "backgroundColor": "var(--color-accent)",
        "color": "var(--color-on-accent)",
        "borderColor": "var(--color-accent)"
      },
      "variant:secondary": {
        "backgroundColor": "var(--color-background-card)",
        "color": "var(--color-text-primary)",
        "borderColor": "color-mix(in srgb, var(--color-text-primary) 50%, var(--color-background-body))"
      },
      "variant:ghost": {
        "backgroundColor": "transparent",
        "color": "var(--color-text-secondary)",
        "borderColor": "color-mix(in srgb, var(--color-text-primary) 50%, var(--color-background-body))"
      },
      "variant:destructive": {
        "backgroundColor": "color-mix(in srgb, var(--color-error) 75%, #000)",
        "color": "#ffffff",
        "borderColor": "color-mix(in srgb, var(--color-error) 75%, #000)"
      },
      "variant:outline": {
        "backgroundColor": "transparent",
        "color": "var(--color-text-primary)",
        "borderColor": "color-mix(in srgb, var(--color-text-primary) 50%, var(--color-background-body))"
      },
      "variant:notch": {
        "backgroundColor": "var(--color-background-card)",
        "color": "var(--color-text-primary)",
        "borderColor": "color-mix(in srgb, var(--color-text-primary) 50%, var(--color-background-body))"
      },
      "elevation:none": {
        "boxShadow": "none"
      },
      "elevation:low": {
        "boxShadow": "none"
      },
      "elevation:med": {
        "boxShadow": "none"
      },
      "elevation:high": {
        "boxShadow": "none"
      }
    },
    "card": {
      "base": {
        "borderRadius": "4px",
        "boxShadow": "none",
        "borderWidth": "2px",
        "borderStyle": "solid",
        "borderColor": "color-mix(in srgb, var(--color-text-primary) 18%, transparent)",
        "backgroundColor": "var(--color-background-card)"
      }
    },
    "badge": {
      "variant:plan": {
        "backgroundColor": "color-mix(in srgb, var(--astryx-theme-dotto-color-plan) 22%, transparent)",
        "color": "var(--astryx-theme-dotto-color-plan)"
      },
      "variant:tool": {
        "backgroundColor": "color-mix(in srgb, var(--astryx-theme-dotto-color-tool) 22%, transparent)",
        "color": "var(--astryx-theme-dotto-color-tool)"
      },
      "variant:file": {
        "backgroundColor": "color-mix(in srgb, var(--astryx-theme-dotto-color-file) 22%, transparent)",
        "color": "var(--astryx-theme-dotto-color-file)"
      },
      "variant:judge": {
        "backgroundColor": "color-mix(in srgb, var(--astryx-theme-dotto-color-judge) 22%, transparent)",
        "color": "var(--astryx-theme-dotto-color-judge)"
      }
    },
    "banner": {
      "base": {
        "borderRadius": "4px",
        "boxShadow": "none"
      }
    },
    "text-input": {
      "base": {
        "borderRadius": "4px",
        "borderWidth": "2px"
      }
    },
    "tooltip": {
      "base": {
        "borderRadius": "4px",
        "boxShadow": "none",
        "borderWidth": "2px",
        "borderStyle": "solid"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": [
      {
        "when": {
          "pointer": "coarse"
        },
        "value": {
          "tokens": {
            "--size-element-sm": "36px",
            "--size-element-md": "44px",
            "--size-element-lg": "44px"
          }
        }
      },
      {
        "when": {
          "motion": "reduce"
        },
        "value": {
          "tokens": {
            "--duration-fast-min": "1ms",
            "--duration-fast": "1ms",
            "--duration-fast-max": "1ms",
            "--duration-medium-min": "1ms",
            "--duration-medium": "1ms",
            "--duration-medium-max": "1ms"
          }
        }
      }
    ]
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 17,
        "ratio": 1.2
      },
      "body": {
        "family": "Geist",
        "fallbacks": "ui-sans-serif, system-ui, sans-serif",
        "weight": "normal"
      },
      "heading": {
        "family": "Geist Pixel Square",
        "fallbacks": "DotGothic16, ui-monospace, monospace",
        "weight": "normal"
      },
      "code": {
        "family": "Geist Mono",
        "fallbacks": "ui-monospace, Menlo, Consolas, monospace",
        "weight": "medium"
      }
    },
    "color": {
      "accent": [
        "#67437d",
        "#d2aaf7"
      ],
      "neutralStyle": "cool",
      "contrast": "standard"
    },
    "radius": {
      "base": 4,
      "multiplier": 0.5
    },
    "motion": {
      "fast": 160,
      "medium": 240,
      "slow": 520,
      "ratio": 0.75
    }
  },

};
